# First remove *all* keybindings
# unbind-key -a
# Now reinsert all the regular tmux keys

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# copy mode commands
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'v

# fast exit pane
bind q killp

# window management
bind c new-window -c "$HOME"
bind w list-windows
bind | split-window
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind -n S-Left  previous-window
bind -n S-Right next-window

# reload config file
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"


